<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>MouseKeyboardMacroRecorder</RootNamespace>
    <AssemblyName>MouseKeyboardMacroRecorder</AssemblyName>
    <ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MouseKeyboardMacroRecorder.Core\MouseKeyboardMacroRecorder.Core.csproj" />
    <PackageReference Include="Material.Icons.WPF" Version="3.0.2" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\favicon.ico" />
    <Resource Include="Assets\favicon.ico">
    </Resource>
  </ItemGroup>
</Project>
